### ISSUE TITLE
a cache write stack

### ISSUE THREAD

**Issue by mingzym** [efengcloud/trafficserver#7]
```
(gdb) bt full
#0  Vol::evac_range (this=0x2af230026940, low=<value optimized out>, high=<value optimized out>, evac_phase=1) at CacheWrite.cc:713
        offset = <value optimized out>
        phase = <value optimized out>
        b = 0x753000002af20030
        first = <value optimized out>
        first_offset = <value optimized out>
        i = -2384
        s = -78143327
        e = -78125919
        si = <value optimized out>
        ei = -2384
#1  0x00000000006c8f46 in Vol::aggWrite (this=<value optimized out>, event=4, e=<value optimized out>) at CacheWrite.cc:1042
        c = <value optimized out>
        __func__ = "aggWrite"
        end = 22175744
        ret = <value optimized out>
        tocall = {<DLL<CacheVC, Continuation::Link_link>> = {head = 0x2b0013187c00}, tail = 0x2b0013187c00}
#2  0x00000000006cb679 in do_write_call (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>)
    at P_CacheInternal.h:920
No locals.
#3  CacheVC::updateVector (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>) at CacheWrite.cc:144
        lock = {m = {m_ptr = 0x2af2140093b0}, lock_acquired = true}
        vec = 1
        ret = 0
        __func__ = "updateVector"
#4  0x000000000063d38e in CacheVC::die (this=0x2b0013187c00) at ../../iocore/cache/P_CacheInternal.h:946
No locals.
#5  0x00000000006ce2ec in calluser (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>)
    at P_CacheInternal.h:856
No locals.
#6  CacheVC::openWriteMain (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>) at CacheWrite.cc:1416
        avail = <value optimized out>
        ntodo = 500268
        total_avail = <value optimized out>
        towrite = 500268
        not_writing = <value optimized out>
#7  0x000000000071aea4 in handleEvent (this=0x2af1c4804010, e=0x2af3d080e600, calling_code=1) at I_Continuation.h:146
No locals.
#8  EThread::process_event (this=0x2af1c4804010, e=0x2af3d080e600, calling_code=1) at UnixEThread.cc:142
        c_temp = <value optimized out>
        lock = {m = {m_ptr = 0x2b04955bc7d0}, lock_acquired = true}
#9  0x000000000071ba0b in EThread::execute (this=0x2af1c4804010) at UnixEThread.cc:193
        done_one = <value optimized out>
        e = <value optimized out>
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x0}, tail = 0x0}
        next_time = 1471239073022499000
#10 0x0000000000719dd2 in spawn_thread_internal (a=0x22de300) at Thread.cc:88
        p = 0x22de300
#11 0x0000003ee6007aa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#12 0x00000034ca6e893d in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) p * this->vio->_cont 
$7 = {<force_VFPT_to_top> = {_vptr.force_VFPT_to_top = 0x73ff90}, handler = (int (Continuation::*)(Continuation *, int, 
    void *)) 0x599680 <HttpTunnel::main_handler(int, void*)>, mutex = {m_ptr = 0x0}, link = {<SLink<Continuation>> = {next = 0x0}, 
    prev = 0x0}}
(gdb) bt
#0  Vol::evac_range (this=0x2af230026940, low=<value optimized out>, high=<value optimized out>, evac_phase=1) at CacheWrite.cc:713
#1  0x00000000006c8f46 in Vol::aggWrite (this=<value optimized out>, event=4, e=<value optimized out>) at CacheWrite.cc:1042
#2  0x00000000006cb679 in do_write_call (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>)
    at P_CacheInternal.h:920
#3  CacheVC::updateVector (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>) at CacheWrite.cc:144
#4  0x000000000063d38e in CacheVC::die (this=0x2b0013187c00) at ../../iocore/cache/P_CacheInternal.h:946
#5  0x00000000006ce2ec in calluser (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>)
    at P_CacheInternal.h:856
#6  CacheVC::openWriteMain (this=0x2b0013187c00, event=<value optimized out>, e=<value optimized out>) at CacheWrite.cc:1416
#7  0x000000000071aea4 in handleEvent (this=0x2af1c4804010, e=0x2af3d080e600, calling_code=1) at I_Continuation.h:146
#8  EThread::process_event (this=0x2af1c4804010, e=0x2af3d080e600, calling_code=1) at UnixEThread.cc:142
#9  0x000000000071ba0b in EThread::execute (this=0x2af1c4804010) at UnixEThread.cc:193
#10 0x0000000000719dd2 in spawn_thread_internal (a=0x22de300) at Thread.cc:88
#11 0x0000003ee6007aa1 in start_thread () from /lib64/libpthread.so.0
#12 0x00000034ca6e893d in clone () from /lib64/libc.so.6
(gdb) 
(gdb) p * this
$4 = {<CacheVConnection> = {<VConnection> = {<Continuation> = {<force_VFPT_to_top> = {_vptr.force_VFPT_to_top = 0x774470}, 
        handler = (int (Continuation::*)(Continuation *, int, void *)) 0x6c8500 <CacheVC::openWriteCloseHeadDone(int, Event*)>, 
        mutex = {m_ptr = 0x2b04955bc7d0}, link = {<SLink<Continuation>> = {next = 0x0}, prev = 0x0}}, lerrno = 0, 
      type = 0}, <No data fields>}, static size_to_init = 376, key = {b = {6096614228117944938, 13711487750256274781}}, 
  first_key = {b = {1832171615603777139, 6434409708724952089}}, earliest_key = {b = {6096614228117944938, 13711487750256274781}}, 
  update_key = {b = {17637014659777408053, 4665277269290660861}}, dir = {w = {41121, 15959, 8192, 0, 4091}}, earliest_dir = {w = {
      59454, 32459, 9535, 0, 13}}, overwrite_dir = {w = {0, 0, 0, 0, 0}}, first_dir = {w = {63550, 5323, 10790, 0, 13}}, 
  _action = {_vptr.Action = 0x7211d0, continuation = 0x2af269f82b90, mutex = {m_ptr = 0x2b04955bc7d0}, cancelled = 0}, 
  request = {<MIMEHdr> = {<HdrHeapSDKHandle> = {m_heap = 0x0}, m_mime = 0x0}, m_http = 0x0, m_url_cached = {<HdrHeapSDKHandle> = {
        m_heap = 0x0}, m_url_impl = 0x0}, m_host_mime = 0x0, m_host_length = 0, m_port = 0, m_target_cached = false, 
    m_target_in_url = false, m_port_in_header = false}, vector = {magic = 0x0, data = {data = 0x2b0013187d10, fast_data = {{
          alternate = {m_alt = 0x0}}, {alternate = {m_alt = 0x0}}, {alternate = {m_alt = 0x0}}, {alternate = {m_alt = 0x0}}}, 
      default_val = 0x11b7338, size = 0, pos = -1}, xcount = 0, vector_buf = {m_ptr = 0x0}}, alternate = {m_alt = 0x2af3f2dac850}, 
  buf = {m_ptr = 0x0}, first_buf = {m_ptr = 0x0}, blocks = {m_ptr = 0x2afd7ec42780}, writer_buf = {m_ptr = 0x0}, cw = {
    m_ptr = 0x2af407b3a760}, od = 0x2af1d6665b40, io = {<AIOCallback> = {<Continuation> = {<force_VFPT_to_top> = {
          _vptr.force_VFPT_to_top = 0x774610}, handler = (int (Continuation::*)(Continuation *, int, 
    void *)) 0x642c90 <AIOCallbackInternal::io_complete(int, void*)>, mutex = {m_ptr = 0x0}, link = {<SLink<Continuation>> = {
            next = 0x0}, prev = 0x0}}, aiocb = {aio_fildes = -1, aio_buf = 0x2afa310c6000, aio_nbytes = 0, 
        aio_offset = 239715949056, aio_reqprio = 0, aio_lio_opcode = 1, aio_state = 0, aio__pad = {0}}, action = {
        _vptr.Action = 0x0, continuation = 0x0, mutex = {m_ptr = 0x0}, cancelled = 0}, thread = 0x2af1c4c08010, then = 0x0, 
      aio_result = 0}, first = 0x0, aio_req = 0x22dc2e0, sleep_time = 0}, alternate_index = 0, opendir_link = {<SLink<CacheVC>> = {
      next = 0x0}, prev = 0x0}, signal_link = {<SLink<CacheVC>> = {next = 0x0}, prev = 0x0}, vio = {_cont = 0x2af269f82610, 
    nbytes = 500268, ndone = 500268, op = 2, buffer = {mbuf = 0x2af1d5d62df0, entry = 0x2af1d5d62e30}, vc_server = 0x2b0013187c00, 
    mutex = {m_ptr = 0x2b04955bc7d0}}, initial_thread = 0x2af1c4804010, frag_type = CACHE_FRAG_TYPE_HTTP, info = 0x0, 
  write_vector = 0x2af1d6665b50, params = 0x0, header_len = 3616, frag_len = 1048504, write_len = 500268, agg_len = 524288, 
  write_serial = 0, vol = 0x2af230026940, last_collision = 0x0, trigger = 0x0, read_key = 0x0, save_handler = (
    int (Continuation::*)(Continuation *, int, void *)) 0x6c8500 <CacheVC::openWriteCloseHeadDone(int, Event*)>, pin_in_cache = 0, 
  start_time = 1471239074384922000, base_stat = 19, recursive = 0, closed = 1, seek_to = 0, offset = 447, writer_offset = 0, 
  length = 500268, doc_pos = 0, write_pos = 0, total_len = 500268, doc_len = 0, update_len = 0, fragment = 0, scan_msec_delay = 0, 
  write_vc = 0x0, hostname = 0x0, host_len = 0, header_to_write_len = 0, header_to_write = 0x0, writer_lock_retry = 0, 
  ssd_vol = 0x0, mts = 0x0, dir_off = 0, {flags = 33, f = {use_first_key = 1, overwrite = 0, close_complete = 0, sync = 0, 
      evacuator = 0, single_fragment = 1, evac_vector = 0, lookup = 0, update = 0, remove = 0, remove_aborted_writers = 0, 
      open_read_timeout = 0, data_done = 0, read_from_writer_called = 0, not_from_ram_cache = 0, rewrite_resident_alt = 0, 
      readers = 0, doc_from_ram_cache = 0, hit_evacuate = 0, force_empty = 0, read_from_ssd = 0, write_into_ssd = 0, 
      ram_fixup = 0, transistor = 0}}, scan_vol_map = 0x0, scan_fix_buffer_offset = 0}
(gdb) p this->

```

**Comment by mingzym** [comment]
```
(gdb) bt full
#0  Vol::evac_range (this=0x2b7de41b4d00, low=<value optimized out>, high=<value optimized out>, evac_phase=1) at CacheWrite.cc:713
        offset = <value optimized out>
        phase = <value optimized out>
        b = 0x5f45444e434d484c
        first = <value optimized out>
        first_offset = <value optimized out>
        i = -2384
        s = -78141983
        e = -78124191
        si = <value optimized out>
        ei = -2384
#1  0x00000000006c8f46 in Vol::aggWrite (this=<value optimized out>, event=1, e=<value optimized out>) at CacheWrite.cc:1042
        c = <value optimized out>
        __func__ = "aggWrite"
        end = 23093248
        ret = <value optimized out>
        tocall = {<DLL<CacheVC, Continuation::Link_link>> = {head = 0x0}, tail = 0x0}
#2  0x00000000006ad370 in CacheSync::mainEvent (this=0x2b7da40c1050, event=2, e=0x2b7dc5e5c9e0) at CacheDir.cc:1231
        dirlen = 12533760
        lock = {m = {m_ptr = 0x2b7de8628dc0}, lock_acquired = true}
        d = 0x2b7de41b4d00
        headerlen = 8192
        B = <value optimized out>
        start = <value optimized out>
        __func__ = "mainEvent"
#3  0x000000000071aea4 in handleEvent (this=0x2b7d416c9010, e=0x2b7dc5e5c9e0, calling_code=2) at I_Continuation.h:146
No locals.
#4  EThread::process_event (this=0x2b7d416c9010, e=0x2b7dc5e5c9e0, calling_code=2) at UnixEThread.cc:142
        c_temp = <value optimized out>
        lock = {m = {m_ptr = 0x2b7dae3d5360}, lock_acquired = true}
#5  0x000000000071ba53 in EThread::execute (this=0x2b7d416c9010) at UnixEThread.cc:221
        done_one = true
        e = <value optimized out>
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x2b7d42fee9c0}, tail = 0x2b7d42fee9c0}
        next_time = 1471259210517361000
#6  0x0000000000719dd2 in spawn_thread_internal (a=0x2cfdbc0) at Thread.cc:88
        p = 0x2cfdbc0
#7  0x0000003beca07aa1 in ?? ()
No symbol table info available.
#8  0x00002b7d426d8700 in ?? ()
No symbol table info available.
#9  0x0000000000000000 in ?? ()
No symbol table info available.
```
